<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dell" ignored="0" name="LoginTest" tests="3" failures="1" timestamp="2019-11-24T23:12:49 EST" time="18.875" errors="0">
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="8.849" classname="tests.LoginTests"/>
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="3.206" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="2.633" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]">
      <![CDATA[java.lang.AssertionError: expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]
at pages.LoginPage.verifyLoginPassword(LoginPage.java:37)
at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:37)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
</testsuite> <!-- LoginTest -->
